# Example Render manifest for deploying CodeShare
# Edit names, branch, and env var references as needed before using.
# This file is optional — you can also configure services via the Render dashboard.

services:
  - type: web
    name: codeshare-backend
    env: node
    region: oregon
    plan: free
    branch: main
    root: server
    buildCommand: ""
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: static
    name: codeshare-frontend
    region: oregon
    plan: free
    branch: main
    root: "."
    buildCommand: "npm install && npm run build"
    publishDirectory: "dist"
    autoDeploy: true
    envVars:
      - key: VITE_BACKEND_URL
        sync: false

# Notes:
# - For security, do NOT put secrets in this file (set them through Render dashboard or CLI instead).
# - Replace 'main' with the branch you deploy from.
# - After deploying, set the env vars (MONGODB_URL, FRONTEND_URL, VITE_BACKEND_URL) in the Render UI.
